### PR TITLE
Fix some bugs and Add PPP

### LINKED ISSUE #148: [PE-D][Tester A] Inconsistent Tips [User Guide]
As shown above, the `Tips` sections states that a patient can have optional medical histories, however, it is also true that the tags prefix when adding a person is also optional:

Thus, perhaps it would be good to also include this information under the `Tips` section for users to understand the system quicker!

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: LHeng1/ped#9

### LINKED ISSUE #155: [PE-D][Tester B] Lack of checks for valid phone numbers
the longest possible phone number is 15 digits long. However I am able to input an extremely long phone number. 

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: TyrusLye/ped#5

### PR DESCRIPTION
**Pull request by angkyakdifp**
Resolves #155, resolves #148

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Email.java [hunk 1]
```diff
@@ -17,6 +17,7 @@ public class Email {
             + "characters.\n"
             + "2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels "
             + "separated by periods.\n"
+            + "3. The maximum size of an email is 255 character.\n"
```
Comment (alvinlim277) [inline src/main/java/seedu/address/model/person/Email.java:20]: I think this should be 'characters' instead of 'character'.

**Review by alvinlim277 — COMMENTED** [review]
Minor grammar issue, otherwise LGTM!

**Review by vansh284 — APPROVED** [review]
LGTM
