### PR TITLE
Bug fix 107 undo redo

### LINKED ISSUE #107: Undo/redo is not working with some commands.
After an `addsc` or `delsc` command, performing `undo` will result in the last change in the address book being undone. The `undo` should undo the `addsc` command instead in this case.

Similarly, for listing patients/specialists. The undo/redo does not seem to account for the change the `FilteredPersonList` in general.

The undo/redo also does not work for the `view`.  So we cannot go back to the previously viewed person.

Commands that require undo/redo integration :

- [x] addsc/delsc
- [x] view
- [x] theme

### LINKED ISSUE #133: [PE-D][Tester D] edit command issue after clear and undo
After clearing and pressing undo, the view box will be empty, resulting in the above error for the edit command which references the person in the view box. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jinyuan0425/ped#6

### LINKED ISSUE #135: [PE-D][Tester E] Undo does not update attributes in the view panel
Steps to reproduce:
1. Enter `edit t/` to remove tag

2. Enter `undo`

Expected result:
View panel and list panel to display tag again

Actual result:
List panel display tag again, view panel did not

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: s0ngyang/ped#4

### LINKED ISSUE #138: [PE-D][Tester E] Cannot edit person after undoing command
Steps to reproduce:
1. Enter `edit t/` to remove tag

2. Enter `undo`

3. Enter `edit p/1234`

Expected result:
Phone number of Alex to be successfully edited

Actual result:
Unable to enter command

Can be a hassle to keep typing `view 1` after undoing in order to edit

Logs:

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: s0ngyang/ped#5

### LINKED ISSUE #142: [PE-D][Tester D] undo command not working as intended.
After the input of "delsc sc/1 sc/2 sc/del", undo only undid the last part of the command (delsc sc/del). However, undo was supposed to undo the previous entry which should mean "delsc sc/1" and "delsc sc/2" should have been undone as well.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jinyuan0425/ped#8

### LINKED ISSUE #154: [PE-D][Tester B] Unclear what commands undo and redo can affect.
In the user guide, the function of undo is "Undo the previous command" and the function of redo is "Redo the previous ‘undo’ ". However it is not mentioned what user commands is undone or redone or which commands these two functions can influence. For example, setting the theme from light to dark is a user command, however, entering undo or redo does not change the current theme to its previous theme.

Setting the theme from dark to light:

After entering the undo command:

The theme is still set to light.

This could be troubling especially with commands that do not have a visual representation, such as the custom shortcuts. The only way to verify if the shortcut still exists is to either test it or attempt to create it again. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: TyrusLye/ped#4

### PR DESCRIPTION
**Pull request by Kokseng1**
Undo/Redo command bugfix, should now always work as intended.
The previous implementation of undo/redo made fixing the bug difficult, so this required redesigning the implementation.
Update DG to reflect the implementation of Undo/redo, improve the UG for undo/redo.
Closes #154, closes #142, closes #138, closes #135, closes #133, closes #107

Big thanks to Vansh for coming up with the main idea and also finding the flaw in my draft

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -44,22 +49,37 @@ public ModelManager(ReadOnlyAddressBook addressBook, ReadOnlyUserPrefs userPrefs
...
     public ModelManager() {
         this(new AddressBook(), new UserPrefs());
     }
 
+    /**
+     * Resets this ModelManager's data to copy another ModelManager's
+     * @param toCopyFrom ModelManager to copy from
+     */
+    public void resetData(ReadOnlyModelManager toCopyFrom) {
+        this.addressBook = toCopyFrom.addressBook;
```
Comment (vansh284) [inline src/main/java/seedu/address/model/ModelManager.java:76]: This section is what is causing the error, the observers are attached to the objects, if you change the objects then the observers are no longer attached to the new objects.
You should use the corresponding set methods instead to mutate the objects directly (tried on my system, seems to be working) e.g.
```
        setAddressBook(toCopyFrom.addressBook);
        setUserPrefs(toCopyFrom.userPrefs);
        updateSelectedPerson(toCopyFrom.selectedPerson);
        updateFilteredPersonList((Predicate<Person>) toCopyFrom.filteredPersons.getPredicate());
        setShortcutSettings(toCopyFrom.userPrefs.getShortcutSettings());
        setTheme(toCopyFrom.themeProperty.getValue());
```
(I'm not sure if the typecast for `Predicate<Person>` will always be valid, maybe add a check for this)

File: src/main/java/seedu/address/model/ModelManager.java [hunk 2]
```diff
@@ -244,26 +264,81 @@ public boolean equals(Object other) {
...
+        FilteredList<Person> filteredListCopy = new FilteredList<Person>(obListCopy.asUnmodifiableObservableList());
+        filteredListCopy.setPredicate(this.filteredPersons.getPredicate());
+        //maybe causing undone states to malfunction
+
+        modelManagerStateList.add(new ReadOnlyModelManager(
+                new AddressBook(this.addressBook),
+                filteredListCopy, //gets edited when new command wrong
+                this.userPrefs.getCopy(),
+                personCopy,
+                this.themeProperty
```
Comment (vansh284) [inline src/main/java/seedu/address/model/ModelManager.java:307]: You forgot to create a copy for the `themeProperty` here, which would also cause problems with undoing/redoing the `theme` command.

**Review by Gavino3o — DISMISSED** [review]
Overall LGTM! I tested it out locally and it works as intended (Really good job bro). Just some minor nit about documentation where I felt it could be worded better. Provided an alternative for consideration. Approved with thanks.

File: docs/UserGuide.md [hunk 3]
```diff
@@ -204,7 +204,9 @@ Examples:
 
 ### Undo previous entry : `undo`
 
-Undo the previous command, stackable. (Able to keep undo-ing till there are no commands left to be undone)
+Undo the previous command, stackable. (Able to keep undo-ing till there are no commands left to be undone).
```
[the remark this answers is not in the document]
Comment (Kokseng1) [reply docs/UserGuide.md]: This is indeed clearer, thanks for the suggestion. I have updated it

**Comment by vansh284** [comment]
The undo/redo seems almost complete. But it seems #142 still causes problems. A `delsc` with a single parameter is undone properly, but `delsc` with multiple parameters didn't seem to be undone when I tested it.
Maybe @alvinlim277 do you have any ideas what could be causing this? Since the behaviour seems unique to deleting multiple shortcuts.

**Comment by Gavino3o** [comment]
> The undo/redo seems almost complete. But it seems #142 still causes problems. A `delsc` with a single parameter is undone properly, but `delsc` with multiple parameters didn't seem to be undone when I tested it. Maybe @alvinlim277 do you have any ideas what could be causing this? Since the behaviour seems unique to deleting multiple shortcuts.

@vansh284 I tested it locally at my side, and it works as intended (if I am not mistaken by the intended behaviour). Can you elaborate more on the test you conducted, and the issue faced?

**Comment by alvinlim277** [comment]
> The undo/redo seems almost complete. But it seems #142 still causes problems. A `delsc` with a single parameter is undone properly, but `delsc` with multiple parameters didn't seem to be undone when I tested it.
> 
> Maybe @alvinlim277 do you have any ideas what could be causing this? Since the behaviour seems unique to deleting multiple shortcuts.

From my knowledge moving model.commit() out of the loop in DeleteShortcutCommand::execute should have fixed the problem, not sure what's still causing it...

File: src/main/java/seedu/address/model/ModelManager.java [hunk 4]
```diff
@@ -44,22 +49,39 @@ public ModelManager(ReadOnlyAddressBook addressBook, ReadOnlyUserPrefs userPrefs
...
         this(new AddressBook(), new UserPrefs());
     }
 
+    /**
+     * Resets this ModelManager's data to copy another ModelManager's
+     * @param toCopyFrom ModelManager to copy from
+     */
+    public void resetData(ReadOnlyModelManager toCopyFrom) {
+        setAddressBook(toCopyFrom.addressBook);
+        setUserPrefs(toCopyFrom.userPrefs);
```
Comment (vansh284) [inline src/main/java/seedu/address/model/ModelManager.java:77]: Over here as well, we need to use the copies rather than the actual objects, since our modelManagerStateList should only have copies of the current model.

```
setUserPrefs(toCopyFrom.userPrefs.getCopy())
updateSelectedPerson(toCopyFrom.selectedPerson == null ? null : toCopyFrom.selectedPerson.getCopy())
```

**Comment by vansh284** [comment]
I tested the bug more extensively and found out the problem was not with multiple shortcuts, it was when I tried to delete a shortcut immediately after doing an undo command. I've identified the problem. @Kokseng1 could you make the changes?

File: docs/UserGuide.md [hunk 5]
```diff
@@ -204,7 +204,9 @@ Examples:
 
 ### Undo previous entry : `undo`
 
-Undo the previous command, stackable. (Able to keep undo-ing till there are no commands left to be undone)
+Undo the previous command, stackable (all commands that were successfully executed previously can be continuously undone until there are no commands left to be undone).
```
Comment (vansh284) [inline docs/UserGuide.md:207]: This updated formulation for the undo seems clearer. Maybe we can follow the same format for the redo part of the UG?

File: docs/UserGuide.md [hunk 6]
```diff
@@ -204,7 +204,9 @@ Examples:
...
+The undo/redo command is affected by all successful commands, whether they change the data or not.
```
Comment (vansh284) [inline docs/UserGuide.md:208]: I think we should only specify this behaviour for the undo command in this section, since we have a separate section to describe the redo behaviour in the UG

File: docs/DeveloperGuide.md [hunk 7]
```diff
@@ -157,39 +157,48 @@ This section describes some noteworthy details on how certain features are imple
...
 
 ![UndoRedoState0](images/UndoRedoState0.png)
 
-Step 2. The user executes `delete 5` command to delete the 5th person in the address book. The `delete` command calls `Model#commitAddressBook()`, causing the modified state of the address book after the `delete 5` command executes to be saved in the `addressBookStateList`, and the `currentStatePointer` is shifted to the newly inserted address book state.
+Step 2. The user executes `delete 5` command to delete the 5th person in the current list. The `delete` command calls `Model#commit()`, causing the modified state of the ModelManager after the `delete 5` command executes to be saved in the `modelManagerStateList`, and the `currentStatePointer` is shifted to the newly inserted ModelManager state.
 
 ![UndoRedoState1](images/UndoRedoState1.png)
 
-Step 3. The user executes `add n/David …​` to add a new person. The `add` command also calls `Model#commitAddressBook()`, causing another modified address book state to be saved into the `addressBookStateList`.
```
Comment (vansh284) [inline docs/DeveloperGuide.md:180]: We can update this to `add -pa n/David ...` to match our application

File: docs/DeveloperGuide.md [hunk 8]
```diff
@@ -202,19 +211,17 @@ The following sequence diagram shows how the undo operation works:
...
+<div markdown="span" class="alert alert-info">:information_source: **Note:** If the `currentStatePointer` is at index `ModelManagerStateList.size() - 1`, pointing to the latest ModelManager state, then there are no undone ModelManager states to restore. The `redo` command uses `ModelManager#canRedo()` to check if this is the case. If so, it will return an error to the user rather than attempting to perform the redo.
 
 </div>
 
-Step 5. The user then decides to execute the command `list`. Commands that do not modify the address book, such as `list`, will usually not call `Model#commitAddressBook()`, `Model#undoAddressBook()` or `Model#redoAddressBook()`. Thus, the `addressBookStateList` remains unchanged.
+Step 5. The user then decides to execute the command `list`. Since this command modifies the ModelManager, `Model#commit()` is called.
```
Comment (vansh284) [inline docs/DeveloperGuide.md:220]: Similarly, we can update this to `list -pa`.

File: docs/DeveloperGuide.md [hunk 9]
```diff
@@ -202,19 +211,17 @@ The following sequence diagram shows how the undo operation works:
...
+Since the `currentStatePointer` is not pointing at the end of the `ModelManagerStateList`, all ModelManager states after the `currentStatePointer` will be purged. Reason: It no longer makes sense to redo the `add n/David …​` command. This is the behavior that most modern desktop applications follow.
```
Comment (vansh284) [inline docs/DeveloperGuide.md:221]: Same as above, `add -pa n/David...`

**Comment by Kokseng1** [comment]
> I tested the bug more extensively and found out the problem was not with multiple shortcuts, it was when I tried to delete a shortcut immediately after doing an undo command.

I can't seem to recreate the bug, maybe you can provide the steps to encounter the bug?

**Comment by vansh284** [comment]
> I can't seem to recreate the bug, maybe you can provide the steps to encounter the bug?

Yes sure, the bug occurs if for example.
1. `addsc sc/del kw/delete`
2. `del 1`
3. `undo`
4. `delsc sc/del`
5. `undo`
6. `del 1` -> Expected behaviour: `del` works since we undoed `delsc`, however, `del` is an "unknown command"

The fix I mentioned earlier should resolve the problem.

File: docs/diagrams/UndoSequenceDiagram.puml [hunk 10]
```diff
@@ -38,6 +38,9 @@ Model -> ModelManager : undo()
 activate ModelManager
 
 ModelManager -> ModelManager :resetData(ReadOnlyModelManager)
+activate ModelManager MODEL_COLOR_T3
+ModelManager -> ModelManager
```
Comment (vansh284) [inline docs/diagrams/UndoSequenceDiagram.puml:42]: I think this should be a `-->` (return arrows should be dashed lines).

**Review by vansh284 — APPROVED** [review]
Just one small nit in the UML diagram, and then good to go!
Also seems you forgot to save the updated `UndoSequenceDiagram` image after editing the `.puml` file.
