### PR TITLE
Resolve duplicate person bug

### LINKED ISSUE #99: Duplicate persons bug
Due to how `Person::isSamePerson` is implemented (it only does a check on the names of the persons being compared), users are unable to add a specialist with the same name as an existing patient. 

image

### PR DESCRIPTION
**Pull request by alvinlim277**
Resolves #99

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -55,18 +55,7 @@ public Set<Tag> getTags() {
...
-     */
-    public boolean isSamePerson(Person otherPerson) {
-        if (otherPerson == this) {
-            return true;
-        }
-
-        return otherPerson != null
-                && otherPerson.getName().equals(getName());
-    }
+    public abstract boolean isSamePerson(Person otherPerson);
```
Comment (vansh284) [inline src/main/java/seedu/address/model/person/Person.java:58]: Nice use of OOP and polymorphism!

**Review by vansh284 — APPROVED** [review]
Neat implementation. LGTM.
